// Curated sites, interconnectors and grid links. Edit here, then run tools/update_osm.py (routes) and tools/build.py.
// Places: substations, landfalls, demand centres (lat, lon)
const P = {
  killingholme:['Killingholme substation, North Lincolnshire',53.65,-0.26],
  creyke:['Creyke Beck substation, East Yorkshire',53.80,-0.42],
  lackenby:['Lackenby substation, Teesside',54.57,-1.13],
  bramford:['Bramford substation, Suffolk',52.07,1.07],
  leiston:['Leiston / Friston substations, Suffolk',52.20,1.55],
  cleve:['Cleve Hill substation, Kent',51.33,0.95],
  heyshamS:['Heysham substation, Lancashire',54.03,-2.88],
  penwortham:['Penwortham substation, Preston',53.74,-2.73],
  bodel:['Bodelwyddan substation, Denbighshire',53.26,-3.50],
  deeside:["Deeside / Connah's Quay substation",53.23,-3.07],
  pentir:['Pentir substation, Gwynedd',53.19,-4.12],
  newdeer:['New Deer substation, Aberdeenshire',57.52,-2.18],
  blackhill:['Blackhillock substation, Moray',57.54,-2.97],
  beauly:['Beauly substation, Highlands',57.48,-4.46],
  denny:['Denny, on the Beauly–Denny line',56.02,-3.90],
  tealing:['Tealing substation, Angus',56.52,-2.98],
  crystal:['Crystal Rig substation, East Lothian',55.88,-2.52],
  cockenzie:['Cockenzie, East Lothian',55.97,-2.97],
  eccles:['Eccles substation, Scottish Borders',55.66,-2.30],
  harker:['Harker substation, Carlisle',54.93,-2.95],
  spittal:['Spittal converter station, Caithness',58.47,-3.44],
  kergord:['Kergord converter station, Shetland',60.30,-1.28],
  bicker:['Bicker Fen substation, Lincolnshire',52.93,-0.20],
  walpole:['Walpole substation, Norfolk',52.72,0.20],
  norwich:['Norwich Main substation',52.60,1.29],
  bolney:['Bolney substation, West Sussex',50.99,-0.20],
  bridgwater:['Shurton substation, near Bridgwater',51.16,-3.05],
  seabank:['Seabank substation, Avonmouth',51.54,-2.67],
  hunterston:['Hunterston converter station, Ayrshire',55.72,-4.90],
  hawthorn:['Hawthorn Pit, County Durham',54.80,-1.36],
  peterheadS:['Peterhead substation',57.48,-1.79],
  fraisthorpe:['Fraisthorpe landfall, East Yorkshire',54.03,-0.21],
  draxS:['Drax substation, North Yorkshire',53.74,-0.99],
  torness:['Torness, East Lothian',55.97,-2.41],
  blyth:['Blyth converter station, Northumberland',55.13,-1.51],
  sellindge:['Sellindge converter station, Kent',51.10,1.00],
  folkestone:['Folkestone, via the Channel Tunnel',51.09,1.14],
  grain:['Isle of Grain, Kent',51.44,0.70],
  richborough:['Richborough, Kent',51.30,1.35],
  chilling:['Chilling, near Fareham',50.85,-1.25],
  auchencrosh:['Auchencrosh converter station, Ayrshire',55.07,-4.97],
  pembrokeS:['Pembroke substation',51.68,-4.99],
  fr1:['Bonningues-lès-Calais, France',50.89,1.77],
  fr2:['Tourbe, Normandy, France',49.15,-0.20],
  fr3:['Coquelles, France',50.93,1.80],
  nl:['Maasvlakte, Netherlands',51.96,4.02],
  be:['Gezelle, near Bruges, Belgium',51.27,3.20],
  no:['Kvilldal, Norway',59.51,6.64],
  dk:['Revsing, Denmark',55.48,9.10],
  de:['Fedderwarden, near Wilhelmshaven, Germany',53.57,8.05],
  ni:['Islandmagee, County Antrim',54.84,-5.77],
  ie1:['Rush North Beach, County Dublin',53.52,-6.10],
  ie2:['Great Island, County Wexford',52.30,-6.97],
  // demand centres
  london:['London and the South East',51.51,-0.13,1],
  midlands:['Birmingham and the Midlands',52.48,-1.90,1],
  manchester:['Greater Manchester',53.48,-2.24,1],
  liverpool:['Merseyside',53.41,-2.98,1],
  leeds:['West Yorkshire',53.80,-1.55,1],
  newcastle:['Tyneside and the North East',54.97,-1.61,1],
  glasgow:['Glasgow and west-central Scotland',55.86,-4.25,1],
  edinburgh:['Edinburgh and the Lothians',55.95,-3.19,1],
  cardiff:['Cardiff and South Wales',51.48,-3.18,1],
  bristol:['Bristol and the South West',51.45,-2.59,1],
  belfast:['Belfast',54.60,-5.93,1],
  dublin:['Dublin',53.35,-6.26,1],
  nwales:['North Wales coast towns',53.30,-3.72,1],
  anglesey:['Anglesey and Gwynedd',53.22,-4.16,1],
  midwales:['Mid Wales towns',52.47,-3.50,1],
  westwales:['Carmarthenshire',51.86,-4.31,1],
  pembs:['Pembrokeshire',51.80,-4.97,1],
  swansea:['Swansea Bay',51.62,-3.94,1]
};
const scotSur = ['harker','manchester'];
const eastSur = ['eccles','newcastle'];

const SITES = [
 // offshore wind
 {id:'hornsea1',n:'Hornsea One',t:'ow',c:[53.885,1.79],mw:1218,on:2019,r:['killingholme'],h:'midlands',note:'About 120 km off the Yorkshire coast. Cables come ashore at Horseshoe Point in Lincolnshire; much of the power is used by Humber industry before the rest heads towards the Midlands.'},
 {id:'hornsea2',n:'Hornsea Two',t:'ow',c:[53.98,1.66],mw:1386,on:2022,r:['killingholme'],h:'midlands',note:'The largest operating offshore wind farm in the world when it opened in 2022.'},
 {id:'hornsea3',n:'Hornsea Three',t:'ow',c:[53.86,2.52],mw:2900,on:2027,st:'con',r:['norwich'],h:'london',note:'Under construction. Its cables land on the north Norfolk coast rather than in Yorkshire.'},
 {id:'doggerA',n:'Dogger Bank A',t:'ow',c:[54.76,1.85],mw:1200,on:2025,r:['creyke'],h:'leeds',note:'First phase of Dogger Bank, which will be the largest offshore wind farm in the world at 3.6 GW across three phases. Turbines began generating in 2023.'},
 {id:'doggerB',n:'Dogger Bank B',t:'ow',c:[54.98,2.06],mw:1200,on:2026,st:'con',r:['creyke'],h:'leeds',note:'Second phase, built alongside phase A and sharing its Creyke Beck connection.'},
 {id:'doggerC',n:'Dogger Bank C',t:'ow',c:[55.21,2.40],mw:1200,on:2027,st:'con',r:['lackenby'],h:'newcastle',sur:['leeds'],note:'Third phase; connects on Teesside rather than East Yorkshire.'},
 {id:'sofia',n:'Sofia',t:'ow',c:[54.93,2.72],mw:1400,on:2026,st:'con',r:['lackenby'],h:'newcastle',sur:['leeds'],note:'Around 195 km offshore on Dogger Bank, among the furthest from shore in the UK.'},
 {id:'triton',n:'Triton Knoll',t:'ow',c:[53.49,0.84],mw:857,on:2022,r:['bicker'],h:'midlands'},
 {id:'racebank',n:'Race Bank',t:'ow',c:[53.27,0.84],mw:573,on:2018,r:['walpole'],h:'midlands'},
 {id:'ea1',n:'East Anglia ONE',t:'ow',c:[52.24,2.49],mw:714,on:2020,r:['bramford'],h:'london'},
 {id:'ea3',n:'East Anglia THREE',t:'ow',c:[52.66,2.83],mw:1400,on:2026,st:'con',r:['bramford'],h:'london',note:'Under construction; first power expected around 2026.'},
 {id:'ea2',n:'East Anglia TWO',t:'ow',c:[52.12,1.98],mw:960,on:2030,st:'dev',r:['leiston','bramford'],h:'london'},
 {id:'gabbard',n:'Greater Gabbard',t:'ow',c:[51.93,1.92],mw:504,on:2012,r:['leiston','bramford'],h:'london'},
 {id:'galloper',n:'Galloper',t:'ow',c:[51.81,2.04],mw:353,on:2018,r:['leiston','bramford'],h:'london'},
 {id:'londonarray',n:'London Array',t:'ow',c:[51.63,1.47],mw:630,on:2013,r:['cleve'],h:'london',note:'In the outer Thames Estuary, feeding almost directly into the London area.'},
 {id:'rampion',n:'Rampion',t:'ow',c:[50.67,-0.27],mw:400,on:2018,r:['bolney'],h:'london',note:'Visible from Brighton. A 1.2 GW extension, Rampion 2, is in development.'},
 {id:'walneyx',n:'Walney Extension',t:'ow',c:[54.09,-3.74],mw:659,on:2018,r:['heyshamS','penwortham'],h:'manchester'},
 {id:'walney',n:'Walney 1 & 2',t:'ow',c:[54.03,-3.47],mw:367,on:2012,r:['heyshamS','penwortham'],h:'manchester'},
 {id:'gym',n:'Gwynt y Môr',t:'ow',c:[53.45,-3.58],mw:576,on:2015,r:['bodel','deeside'],h:'liverpool',note:'Off the North Wales coast between Llandudno and Rhyl. North Wales uses some; most flows east into Merseyside and Cheshire.'},
 {id:'awel',n:'Awel y Môr',t:'ow',c:[53.42,-3.86],mw:775,on:2030,st:'dev',r:['bodel','deeside'],h:'liverpool',note:'Consented extension to Gwynt y Môr, sharing the Bodelwyddan connection area.'},
 {id:'burbo',n:'Burbo Bank Extension',t:'ow',c:[53.54,-3.26],mw:258,on:2017,r:['bodel','deeside'],h:'liverpool'},
 {id:'mona',n:'Mona',t:'ow',c:[53.78,-3.55],mw:1500,on:2030,st:'dev',r:['bodel','deeside'],h:'manchester',note:'In development in the Irish Sea, around 30 km off the North Wales coast. It would come ashore in Conwy county and connect at Bodelwyddan.'},
 {id:'morgan',n:'Morgan',t:'ow',c:[53.97,-3.86],mw:1500,on:2030,st:'dev',r:['penwortham'],h:'manchester',note:'In development in the Irish Sea; would connect at Penwortham near Preston.'},
 {id:'morayeast',n:'Moray East',t:'ow',c:[58.19,-2.70],mw:950,on:2022,r:['newdeer','denny'],h:'glasgow',sur:scotSur},
 {id:'moraywest',n:'Moray West',t:'ow',c:[58.06,-3.13],mw:882,on:2025,r:['blackhill','beauly','denny'],h:'glasgow',sur:scotSur},
 {id:'beatrice',n:'Beatrice',t:'ow',c:[58.27,-3.07],mw:588,on:2019,r:['blackhill','beauly','denny'],h:'glasgow',sur:scotSur},
 {id:'seagreen',n:'Seagreen',t:'ow',c:[56.60,-1.75],mw:1075,on:2023,r:['tealing'],h:'edinburgh',sur:eastSur,note:"Scotland's largest offshore wind farm."},
 {id:'inchcape',n:'Inch Cape',t:'ow',c:[56.47,-2.24],mw:1080,on:2027,st:'con',r:['cockenzie'],h:'edinburgh',sur:eastSur,note:'Under construction off Angus; connects at the site of the old Cockenzie coal station.'},
 {id:'nng',n:'Neart na Gaoithe',t:'ow',c:[56.27,-2.32],mw:450,on:2024,r:['crystal'],h:'edinburgh',sur:eastSur},
 {id:'berwick',n:'Berwick Bank',t:'ow',c:[56.08,-1.98],mw:4100,on:2033,st:'dev',r:['eccles'],h:'newcastle',note:'In development; one of the largest offshore wind projects proposed anywhere. Timing depends on grid reinforcement.'},
 // onshore wind
 {id:'whitelee',n:'Whitelee',t:'nw',c:[55.68,-4.27],mw:539,on:2009,r:[],h:'glasgow',sur:scotSur,note:"The UK's largest onshore wind farm, on Eaglesham Moor just south of Glasgow."},
 {id:'clyde',n:'Clyde',t:'nw',c:[55.45,-3.66],mw:522,on:2012,r:[],h:'glasgow',sur:scotSur,note:'Spread along the M74 near Abington.'},
 {id:'viking',n:'Viking',t:'nw',c:[60.34,-1.36],mw:443,on:2024,r:['kergord','spittal','blackhill','beauly','denny'],h:'glasgow',sur:scotSur,note:'Shetland was not connected to the GB grid at all until 2024. Viking’s power now crosses a 260 km subsea cable to Caithness.'},
 {id:'penycymoedd',n:'Pen y Cymoedd',t:'nw',c:[51.70,-3.62],mw:228,on:2017,r:[],h:'cardiff',note:'The largest onshore wind farm in England and Wales.'},
 // nuclear
 {id:'heysham1',n:'Heysham 1',t:'nu',c:[54.035,-2.905],mw:1150,on:1983,off:2028,r:['penwortham'],h:'manchester',note:'Advanced gas-cooled reactors. Scheduled to close in 2028.'},
 {id:'heysham2',n:'Heysham 2',t:'nu',c:[54.022,-2.935],mw:1230,on:1988,off:2030,r:['penwortham'],h:'manchester',note:'Scheduled to close in 2030.'},
 {id:'hartlepool',n:'Hartlepool',t:'nu',c:[54.635,-1.18],mw:1185,on:1983,off:2028,r:[],h:'newcastle',sur:['leeds'],note:'Scheduled to close in 2028.'},
 {id:'torness',n:'Torness',t:'nu',c:[55.97,-2.41],mw:1190,on:1988,off:2030,r:[],h:'edinburgh',sur:eastSur,note:"Scotland's last nuclear station; scheduled to close in 2030."},
 {id:'sizewellb',n:'Sizewell B',t:'nu',c:[52.213,1.625],mw:1198,on:1995,off:2035,r:['leiston','bramford'],h:'london',note:"The UK's only pressurised water reactor. Scheduled to close in 2035, though EDF is seeking a 20-year extension."},
 {id:'hpc',n:'Hinkley Point C',t:'nu',c:[51.208,-3.14],mw:3260,on:2030,st:'con',cf:.9,r:['bridgwater','seabank'],h:'bristol',sur:['midlands'],note:'Two large EPR reactors under construction in Somerset. First power is expected around 2030 after repeated delays. A new 400 kV line runs up to Seabank near Avonmouth.'},
 {id:'sizewellc',n:'Sizewell C',t:'nu',c:[52.235,1.598],mw:3200,on:2039,st:'con',cf:.9,r:['leiston','bramford'],h:'london',note:'Final investment decision was taken in 2025. A near-copy of Hinkley Point C, next to Sizewell B; power expected in the late 2030s.'},
 {id:'wylfa',n:'Wylfa (small modular reactors)',t:'nu',c:[53.416,-4.482],mw:1410,on:2035,st:'dev',cf:.9,r:['pentir','deeside'],h:'manchester',note:'Great British Energy – Nuclear chose Wylfa in November 2025 for the UK’s first small modular reactors, and signed a contract with Rolls-Royce SMR in April 2026 to design and build three 470 MW units. Power is targeted from the mid-2030s. The government says the first three could power around three million homes, and the site could host up to eight reactors. Power would use the existing 400 kV line from the old Wylfa station across Anglesey to Pentir, then east along the North Wales coast.'},
 // gas
 {id:'pembroke',n:'Pembroke',t:'gas',c:[51.683,-4.99],mw:2200,on:2012,r:[],h:'cardiff',sur:['bristol'],note:'One of the largest gas-fired power stations in Europe.'},
 {id:'connahsquay',n:"Connah's Quay",t:'gas',c:[53.231,-3.081],mw:1380,on:1996,r:[],h:'liverpool'},
 {id:'peterhead',n:'Peterhead',t:'gas',c:[57.476,-1.787],mw:1180,on:2000,r:['tealing'],h:'edinburgh',note:'Proposed site for one of the first gas plants with carbon capture.'},
 {id:'saltend',n:'Saltend',t:'gas',c:[53.736,-0.245],mw:1200,on:2000,r:['creyke'],h:'leeds'},
 {id:'staythorpe',n:'Staythorpe',t:'gas',c:[53.074,-0.857],mw:1750,on:2010,r:[],h:'midlands'},
 {id:'grainpp',n:'Grain',t:'gas',c:[51.446,0.713],mw:1275,on:2010,r:[],h:'london'},
 {id:'westburton',n:'West Burton B',t:'gas',c:[53.36,-0.81],mw:1332,on:2013,r:[],h:'midlands'},
 {id:'didcot',n:'Didcot B',t:'gas',c:[51.623,-1.266],mw:1440,on:1998,r:[],h:'london'},
 {id:'keadby2',n:'Keadby 2',t:'gas',c:[53.595,-0.745],mw:840,on:2023,r:[],h:'leeds',note:'Opened in 2023; among the most efficient gas plants in Europe.'},
 {id:'carrington',n:'Carrington',t:'gas',c:[53.433,-2.406],mw:884,on:2016,r:[],h:'manchester'},
 {id:'ballylumford',n:'Ballylumford',t:'gas',c:[54.843,-5.795],mw:700,on:2003,r:[],h:'belfast',note:"Northern Ireland's largest power station. NI runs its own grid, linked to Scotland by the Moyle interconnector."},
 // biomass
 {id:'drax',n:'Drax',t:'bio',c:[53.736,-0.996],mw:2600,on:2013,r:[],h:'leeds',sur:['midlands'],note:"The UK's largest power station, now burning imported wood pellets in four converted coal units. Eastern Green Link 2 will bring Scottish wind power ashore nearby."},
 {id:'lynemouth',n:'Lynemouth',t:'bio',c:[55.20,-1.52],mw:420,on:2018,r:[],h:'newcastle'},
 // hydro and pumped storage
 {id:'dinorwig',n:'Dinorwig',t:'hy',ps:1,c:[53.118,-4.114],mw:1728,on:1984,r:['pentir','deeside'],h:'manchester',note:'Pumped storage inside Elidir Fawr. It pumps water uphill when power is cheap and can release it at full power within about a minute to meet peaks. It stores electricity rather than creating it, and is a net user overall.'},
 {id:'ffestiniog',n:'Ffestiniog',t:'hy',ps:1,c:[52.98,-3.965],mw:360,on:1963,r:['deeside'],h:'liverpool',note:"The UK's first major pumped storage station."},
 {id:'cruachan',n:'Cruachan',t:'hy',ps:1,c:[56.39,-5.11],mw:440,on:1965,r:[],h:'glasgow',note:'The "hollow mountain" pumped storage station on Loch Awe. A 600 MW expansion is planned.'},
 {id:'foyers',n:'Foyers',t:'hy',ps:1,c:[57.25,-4.49],mw:300,on:1975,r:['beauly','denny'],h:'glasgow'},
 {id:'coireglas',n:'Coire Glas',t:'hy',ps:1,c:[57.02,-4.87],mw:1300,on:2031,st:'dev',r:['beauly','denny'],h:'glasgow',note:'Planned pumped storage near Loch Lochy — the first large scheme in the UK for about 40 years. It would soak up surplus Scottish wind.'},
 // smaller Welsh sites (mostly on the local distribution network)

 {id:'northhoyle',n:'North Hoyle',t:'ow',c:[53.42,-3.44],mw:60,on:2003,local:1,r:['bodel'],h:'nwales',note:"Wales's first offshore wind farm, off Prestatyn."},
 {id:'rhylflats',n:'Rhyl Flats',t:'ow',c:[53.37,-3.66],mw:90,on:2009,local:1,r:['bodel'],h:'nwales'},
 {id:'erebus',n:'Erebus (floating wind)',t:'ow',c:[51.45,-5.62],mw:100,on:2029,st:'dev',r:['pembrokeS'],h:'pembs',note:'A floating offshore wind demonstrator about 40 km off Pembrokeshire, a forerunner of larger Celtic Sea projects.'},
 {id:'morlais',n:'Morlais',t:'ti',c:[53.31,-4.72],mw:240,on:2027,st:'dev',r:[],h:'anglesey',note:'A tidal stream zone off Holy Island, Anglesey, run by Menter Môn. Developers can install turbines up to 240 MW in total; the first devices are due in the next few years.'},
 {id:'clocaenog',n:'Clocaenog Forest',t:'nw',c:[53.06,-3.47],mw:96,on:2020,local:1,r:['bodel'],h:'nwales',note:'One of the largest onshore wind farms in Wales, in forestry above Denbigh.'},
 {id:'brechfa',n:'Brechfa Forest West',t:'nw',c:[51.95,-4.22],mw:57,on:2018,local:1,r:[],h:'westwales'},
 {id:'alltwalis',n:'Alltwalis',t:'nw',c:[51.99,-4.30],mw:23,on:2009,local:1,r:[],h:'westwales'},
 {id:'mynyddygwair',n:'Mynydd y Gwair',t:'nw',c:[51.72,-3.97],mw:34,on:2018,local:1,r:[],h:'swansea'},
 {id:'cefncroes',n:'Cefn Croes',t:'nw',c:[52.37,-3.78],mw:59,on:2005,local:1,r:[],h:'midwales'},
 {id:'carno',n:'Carno',t:'nw',c:[52.55,-3.55],mw:34,on:1996,local:1,r:[],h:'midwales'},
 {id:'garreglwyd',n:'Garreg Lwyd Hill',t:'nw',c:[52.36,-3.23],mw:34,on:2017,local:1,r:[],h:'midwales'},
 {id:'rheidol',n:'Rheidol',t:'hy',c:[52.40,-3.87],mw:49,on:1962,local:1,r:[],h:'midwales',note:'The largest conventional hydro scheme in Wales, using a chain of reservoirs in the Rheidol valley.'},
 {id:'maentwrog',n:'Maentwrog',t:'hy',c:[52.94,-4.00],mw:30,on:1928,local:1,r:[],h:'anglesey',note:'Fed by Llyn Trawsfynydd.'},
 {id:'dolgarrog',n:'Dolgarrog',t:'hy',c:[53.19,-3.84],mw:33,on:1907,local:1,r:[],h:'nwales',note:'Fed by reservoirs in the Carneddau above the Conwy valley.'},
 {id:'cwmdyli',n:'Cwm Dyli',t:'hy',c:[53.05,-4.03],mw:10,on:1906,local:1,r:[],h:'anglesey',note:'Below Snowdon; one of the oldest hydro stations in Britain still running.'},
 // solar
 {id:'clevehill',n:'Cleve Hill',t:'so',c:[51.33,0.93],mw:373,on:2024,r:['cleve'],h:'london',note:'One of the largest solar farms in the UK, with battery storage alongside.'}
];

// Interconnectors (a = abroad end, g = GB end). dir: import / export / both
const LINKS = [
 {id:'ifa',n:'IFA',t:'ic',mw:2000,on:1986,a:'fr1',g:'sellindge',h:'london',dir:'import',country:'France',note:'The oldest link, laid in 1986. GB usually imports French nuclear power through it, especially in winter.'},
 {id:'ifa2',n:'IFA2',t:'ic',mw:1000,on:2021,a:'fr2',via:[[50.35,-0.75]],g:'chilling',h:'london',dir:'import',country:'France',note:'Usually carries French power into southern England.'},
 {id:'eleclink',n:'ElecLink',t:'ic',mw:1000,on:2022,a:'fr3',g:'folkestone',h:'london',dir:'import',country:'France',note:'Runs through the Channel Tunnel rather than under the sea bed.'},
 {id:'britned',n:'BritNed',t:'ic',mw:1000,on:2011,a:'nl',via:[[51.75,2.4]],g:'grain',h:'london',dir:'both',country:'the Netherlands',note:'Flows both ways depending on prices; GB is more often importing.'},
 {id:'nemo',n:'Nemo Link',t:'ic',mw:1000,on:2019,a:'be',via:[[51.35,2.2]],g:'richborough',h:'london',dir:'both',country:'Belgium',note:'Flows both ways depending on prices.'},
 {id:'nsl',n:'North Sea Link',t:'ic',mw:1400,on:2021,a:'no',via:[[58.9,5.4],[56.6,1.2]],g:'blyth',h:'newcastle',dir:'import',country:'Norway',note:'At about 720 km, one of the longest subsea power cables in the world. GB mostly imports Norwegian hydro; when GB is very windy it can send power the other way, letting Norway save water in its reservoirs.'},
 {id:'viking',n:'Viking Link',t:'ic',mw:1400,on:2023,a:'dk',via:[[55.25,6.8],[53.75,1.4]],g:'bicker',h:'midlands',dir:'both',country:'Denmark',note:'At about 765 km, the longest land and subsea interconnector in the world when it opened. Often brings in Danish wind power.'},
 {id:'neuconnect',n:'NeuConnect',t:'ic',mw:1400,on:2028,st:'con',a:'de',via:[[54.0,6.6],[52.5,2.8],[51.62,1.3]],g:'grain',h:'london',dir:'both',country:'Germany',note:"Under construction: the UK's first direct power link to Germany."},
 {id:'moyle',n:'Moyle',t:'ic',mw:500,on:2002,a:'ni',g:'auchencrosh',h:'glasgow',fh:'belfast',dir:'export',country:'Northern Ireland',note:'Links the GB grid to the separate all-island grid. Power usually flows from Scotland to Northern Ireland.'},
 {id:'ewic',n:'East–West Interconnector',t:'ic',mw:500,on:2012,a:'ie1',via:[[53.42,-4.6]],g:'deeside',h:'liverpool',fh:'dublin',dir:'export',country:'Ireland',note:'Comes ashore near Prestatyn and connects at Deeside. Power usually flows from GB to Ireland.'},
 {id:'greenlink',n:'Greenlink',t:'ic',mw:500,on:2025,a:'ie2',via:[[51.78,-5.65]],g:'pembrokeS',h:'cardiff',fh:'dublin',dir:'export',country:'Ireland',note:'Energised in 2025. Expected mostly to carry power from GB to Ireland.'}
];
// Big internal "bootstraps" moving power north to south
const GRID = [
 {id:'western',n:'Western HVDC Link',t:'grid',mw:2250,on:2019,pts:['hunterston',[55.2,-5.28],[54.45,-4.05],[53.62,-3.35],'deeside'],note:'A subsea cable down the west coast carrying surplus Scottish power straight to Deeside in North Wales, bypassing congested lines on land.'},
 {id:'shetland',n:'Shetland HVDC link',t:'grid',mw:600,on:2024,pts:['kergord',[59.5,-2.1],[58.75,-3.05],'spittal'],note:'The first cable connecting Shetland to the GB grid, carrying power from Viking wind farm.'},
 {id:'cmlink',n:'Caithness–Moray link',t:'grid',mw:1200,on:2019,pts:['spittal',[58.05,-3.35],'blackhill'],note:'Carries northern Scottish power across the Moray Firth.'},
 {id:'egl1',n:'Eastern Green Link 1',t:'grid',mw:2000,on:2029,st:'con',pts:['torness',[55.75,-1.85],[55.1,-1.15],'hawthorn'],note:'Under construction: a subsea cable from East Lothian to County Durham to move Scottish wind power south.'},
 {id:'egl2',n:'Eastern Green Link 2',t:'grid',mw:2000,on:2029,st:'con',pts:['peterheadS',[57.0,-1.15],[55.5,-0.75],[54.4,-0.12],'fraisthorpe','draxS'],note:'Under construction: about 500 km from Peterhead to near Drax in Yorkshire, the largest electricity transmission project in Britain.'}
];

